### ISSUE TITLE
Impossible to enable CAS authentification

### ISSUE THREAD

**Issue by bfontaine** [patrickpollet/mahara_plugin_auth_cas#2]
Hello, I've installed your CAS plugin on my Mahara installation (latest, v1.5.1), I've followed your instructions, but when I need to choose an “authentification plugin”, CAS is disabled, and it says: “CAS - You can have only one instance of the CAS authentification plugin”.
Any idea ?

**Comment by justMe123** [comment]
Had this same problem.  It is listed in the drop down but greyed out.  In the help box for the plugin list I found this clue:

"Some methods are disabled because their required PHP extensions are missing or the outgoing connection to the external sources cannot be established. For example, the Persona authentication plugin needs the cURL PHP extension and the HTTPS connection to verifier.login.persona.org."

You are missing a php extension.  Once you put this in place is will be available and work.

**Comment by patrickpollet** [comment]
You are presumably missing the php ldap extension
